### ISSUE TITLE
question on the license

### ISSUE THREAD

**Issue by hgkamath** [PhantomUIx/core#7]
I chanced upon your project while browsing for open-source and cross-platform GUI toolkits.
Firstly, thank you for your contribution. 

This is a touchy topic, and I apologize in advance, just in case .
Its your baby, so its your right to license it as you see fit. 

I suspect the strong copyleft stickiness of the GPL may deter adoption.  
The intention behind using a graphics tool kit is to seldom alter it oneself but to use it as a statically or dynamically linked library, 
I think LGPL or other liberal licenses would lead to more adoption.

Please double check me, but I think other graphics GNU-license projects also do linking exemption
QT early-minor-versions and leading-version-6.7 ([link](https://code.qt.io/cgit/qt/qtbase.git/tree/LICENSES/Qt-GPL-exception-1.0.txt?h=6.7)) and gtk ([link](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/COPYING?ref_type=heads))
There's also lapce/floem (MIT) and linebender/xilem (Apache2) .

Q1) Is the current license temporary until a time when you may consider relicensing as the project matures? 

Q2) I guess its too early for howto-s and api-documentation links. correct?

Feel free to close the issue, after you reply. Thanks in advance.

**Comment by RossComputerGuy** [comment]
We have relicensed under MIT
